version: "3"
services:
  paciofs:
    build:
      # allows us to copy our sibling directories
      context: ..
      # relative to context
      dockerfile: paciofs-docker/Dockerfile
    image: paciofs/paciofs:latest
    ports:
      # http
      - "8080:8080"
      # https
      - "8081:8081"
      # remoting
      - "30552:30552"
      # management
      - "30558:30558"
      # multichain
      - "30771:30771"
