version: "3"
services:
  paciofs:
    build:
      # allows us to copy our sibling directories
      context: ..
      # relative to context
      dockerfile: paciofs-docker/Dockerfile
    image: paciofs/paciofs:latest
    ports:
      - "2552:2552"
      - "8080:8080"
      - "8558:8558"
