dist: xenial

language: java
jdk: openjdk8

addons:
  apt:
    packages:
      - build-essential
      - cmake
      - libfuse-dev

services:
  - docker

script:
  # build the docker image
  - docker build --tag paciofs/paciofs paciofs-docker
