dist: xenial

language: java
jdk: openjdk8

addons:
  apt:
    packages:
      - cmake
      - libfuse-dev

services:
  - docker

before_install:
  # install go
  - wget --output-document go.tar.gz --quiet https://dl.google.com/go/go1.11.3.linux-amd64.tar.gz
  - sudo tar --directory /usr/local --extract --file go.tar.gz
  - rm go.tar.gz
  - export GOPATH="${HOME}/go"
  - export GOBIN="${GOPATH}/bin"
  - export PATH="${PATH}:/usr/local/go/bin:${GOBIN}"

  # install dep
  - mkdir -p ${GOBIN}
  - export DEP_RELEASE_TAG="v0.5.0"
  - curl --silent https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

  # install protoc and headers
  - export PROTOBUF_VERSION=3.6.1
  - wget --output-document protobuf.tar.gz --quiet https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOBUF_VERSION}/protobuf-all-${PROTOBUF_VERSION}.tar.gz
  - tar --extract --file protobuf.tar.gz
  - rm protobuf.tar.gz
  - wget --output-document protoc.zip --quiet https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOBUF_VERSION}/protoc-${PROTOBUF_VERSION}-linux-x86_64.zip
  - unzip protoc.zip -d protobuf-${PROTOBUF_VERSION} bin/protoc
  - rm protoc.zip

  # install MultiChain
  - export MULTICHAIN_VERSION="2.0-beta-1"
  - wget --output-document multichain.tar.gz --quiet https://www.multichain.com/download/multichain-${MULTICHAIN_VERSION}.tar.gz
  - sudo tar --directory /usr/local --extract --file multichain.tar.gz
  - rm multichain.tar.gz
  - export MULTICHAIN_PATH="/usr/local/multichain-${MULTICHAIN_VERSION}"

  # install specific version of commons-exec
  - export COMMONS_EXEC_VERSION="42eb77c321f7dc17aaff45e45ac1179256517005"
  - wget --output-document commons-exec.zip --quiet https://github.com/apache/commons-exec/archive/${COMMONS_EXEC_VERSION}.zip
  - unzip commons-exec.zip
  - rm commons-exec.zip
  - cd commons-exec-${COMMONS_EXEC_VERSION}
  - mvn install --define maven.compiler.source=1.8 --define maven.compiler.target=1.8 --define skipTests=true --define maven.javadoc.skip=true --batch-mode
  - cd ..
  - rm -rf commons-exec-${COMMONS_EXEC_VERSION}


install:
  - mvn install --define skipTests=true --define maven.javadoc.skip=true --define protobuf.protoc=protobuf-${PROTOBUF_VERSION}/bin/protoc --define protobuf.include.dirs=protobuf-${PROTOBUF_VERSION}/src --batch-mode --show-version

script:
  # run tests
  - mvn test --define protobuf.protoc=protobuf-${PROTOBUF_VERSION}/bin/protoc --define protobuf.include.dirs=protobuf-${PROTOBUF_VERSION}/src --batch-mode

  # build the docker image
  - docker-compose --file ./paciofs-docker/docker-compose.yaml build

  # start and stop PacioFS
  - mvn --projects paciofs-server exec:java@run-server &
  - MVN_PID=$!
  - sleep 15s

  # simple query with default parameters
  - ${MULTICHAIN_PATH}/multichain-cli paciofs -rpcuser=rpcuser -rpcpassword=rpcpassword -rpconnect=localhost -rpcport=8332 getblockchaininfo; CLI_EXIT=$?

  # wait for everyting to shut down
  - kill ${MVN_PID}; wait ${MVN_PID}; MVN_EXIT=$?

  # JVM return code when sent SIGTERM
  - test "143" -eq "${MVN_EXIT}"

  # exit with the multichain-cli exit code
  - exit ${CLI_EXIT}
