dist: xenial

language: java
jdk: openjdk8

addons:
  apt:
    packages:
      - cmake
      - libfuse-dev

services:
  - docker

before_install:
  # install go
  - wget --output-document go.tar.gz --quiet https://dl.google.com/go/go1.11.3.linux-amd64.tar.gz
  - sudo tar --directory /usr/local --extract --file go.tar.gz
  - rm go.tar.gz
  - export GOPATH="${HOME}/go"
  - export GOBIN="${GOPATH}/bin"
  - export PATH="${PATH}:/usr/local/go/bin:${GOBIN}"

  # install dep
  - mkdir -p ${GOBIN}
  - export DEP_RELEASE_TAG="v0.5.0"
  - curl --silent https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

  # install protoc and headers
  - export PROTOBUF_VERSION=3.6.1
  - wget --output-document protobuf.tar.gz --quiet https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOBUF_VERSION}/protobuf-all-${PROTOBUF_VERSION}.tar.gz
  - tar xf protobuf.tar.gz
  - rm protobuf.tar.gz
  - wget --output-document protoc.zip --quiet https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOBUF_VERSION}/protoc-${PROTOBUF_VERSION}-linux-x86_64.zip
  - unzip protoc.zip -d protobuf-${PROTOBUF_VERSION} bin/protoc
  - rm protoc.zip

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dprotobuf.protoc=protobuf-${PROTOBUF_VERSION}/bin/protoc -Dprotobuf.include.dirs=protobuf-${PROTOBUF_VERSION}/src --batch-mode --show-version

script:
  # run tests
  - mvn test -Dprotobuf.protoc=protobuf-${PROTOBUF_VERSION}/bin/protoc -Dprotobuf.include.dirs=protobuf-${PROTOBUF_VERSION}/src --batch-mode

  # build the docker image
  - docker-compose --file ./paciofs-docker/docker-compose.yaml build
